version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: edu-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: education
    ports:
      - "5545:5546"
    volumes:
      - edu-db-data:/var/lib/postgresql/data

volumes:
  edu-db-data:
